---
title: "Introduction to python"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, fig.width = 5, fig.height = 5, fig.align = 'center', eval = T, collapse = T)
```

Python is an easy to learn, powerful programming language. It has efficient high-level data structures and a simple but effective approach to object-oriented programming. Python’s elegant syntax and dynamic typing, together with its interpreted nature, make it an ideal language for scripting and rapid application development in many areas on most platforms. Like R, python is an interpreted programming language.

# First steps

We are going to start with basic python instructions. We can either open `spyder` or work from python's interactive prompt. To open the interactive prompt, open the anaconda prompt and type `python`.

```{python}
x = 2 + 2
print x
```

Notice the syntax of `print`. In python 3.X, `print()` is a function.

We should start introducing python's built-in data types. 

## Numbers

There are three basic numeric types in python: `int`, `float` and `complex`. Variables in python are created when you assign a value to them.

```{python}
x = -1      # int
y = 3.14    # float
z = 1 + 2j  # complex
```

Te verify the type of a variable, use the function `type()`

```{python}
print type(x)
print type(y)
print type(z)
```

In python we have to be careful with variable types. For example,

```{python}
a = 21
b = a/6

print b
```

Were you expecting something else? 

```{python}
print type(b)
```

Since `a` was `int`, and `6` was also `int`, python expected an integer result. Let's try something else.

```{python}
b = a/6.0
print b
print type(b)
```

This means that python automatically converts the ouput to the common type with more precision. 

There are times when we want to specify a type on to a variable. This can be done with casting.

```{python}
x = complex(-1)
print x

y = float("3.14")
print y

z = int(-1.0)
print z
```

## Bools

The simplest build-in type in Python is the bool type, it represents the truth values `False` and `True`. 

```{python}
b = True
print type(b)
```

## Strings

String literals in python are surrounded by either single quotation marks, or double quotation marks (like in R)

`'hello'` is the same as `"hello"`.

Like many other popular programming languages, strings in Python are arrays of bytes representing unicode characters.

We can use square brackets to access elements of a string.

```{python}
a = "Hello, World!"
print a[1] 
```

Ups! were you expecting something else? Yes, indexing in python starts with 0. 

We can also concatenate strings in many different ways.

```{python}
print a[0:5], " everybody"

s = a[0:5] + " everybody"
print s

s = "%s everybody... and look, %d is an integer, %f is a float, and %.2f is a pretier float."% (a[0:5], 5, 5.67, 1.6180)
print s
```

There are some useful functions to use with string variables.

```{python}
s = "   Hello, World!  "
print s
s = s.strip()
print s
print s.lower()
print s.upper()
print s.replace("H", "J")
print s.split(",")
```

The function `input()` prompts the user for a string. It is very useful to create simple interactive programs.

```{python, eval = F}
print "Who are you?"
name = input()
print "Hi there, " + name + "!"
```

You can save these three lines in a new file `first_script.py`, and in anaconda's prompt, type `python first_scrip.py`.

# Operators

Here we will see some common python operators.

## Arithmetic

These are valid only with numeric values

```{python}
x = 3.14
y = 1.62

print x+y 

print x-y

print x*y

print x/y

print x%y #Modulus

print x**y #Exponentiation
```

## Assignment

```{python}
x += 3
print x

x -= 3
print x

x *= 3
print x

x /= 3
print x

x **= 3
print x

x %= 3
print x
```

## Comparison

```{python}
x = 3.14
y = 1.62

print x == y
print x != y
print x > y
print x < y
print x >= y
print x <= y
```

## Logical

```{python}
x = 3.14
y = 1.62

print x<5 and y<10
print x<5 or y>4
print not(x<5 and y<10)
```

# Collections

There are four collection data types in the Python programming language: List, Tuple, Set and Dictionary.

## List

A list is a collection which is ordered and changeable. In Python lists are written with square brackets `[]`. Elements in a list need not all have the same type.

```{python}
list1 = [5, 12, 13, 14]
print list1

list2 = ['red', 'blue', 'green']
print list2

list3 = [1, 'red', 5.2]
print list3
```

We can change the value of items in a list.

```{python}
list3 = [1, 'red', 5.2]
list3[0] = 24

print list3
print len(list3)
```

There is a set of built-in methods to be used with list. Here are some examples.

```{python}
thislist = [] #empty list

thislist.append("apple")
print thislist

thislist.insert(1, "cherry")
print thislist

item = thislist.pop()
print thislist
print item

otherlist = ["banana", "orange"]
thislist.extend(otherlist)
print thislist

print thislist.index("banana")

```

We can also use operators `+` (concatenate) and `*` (repeat) in lists.

## Tuple

A tuple is a collection which is ordered and unchangeable. In Python tuples are written with round brackets `()`. Tuples are immutable (i.e. you cannot change its content once created) and can hold mix data types.

```{python}
thistuple = ("apple", "banana", "cherry")
print(thistuple)

print thistuple + ("orange", "grapes") 
print thistuple*3
```

## Python indexing

In python, arrays (string, list, tuple, etc) con be accessed using indexing.
Indices start with 0 from the left side and -1 when starting from the right side.

Here are some examples
```{python}
s = "hey there"
print s[0]
print s[-1]
print s[1:3]
print s[5:]
print s[:-3]
```

# Control structures

Python relies on indentation, using whitespace, to define scope in the code. Other programming languages often use curly-brackets for this purpose. 

## if

```{python}
x = 3.14
y = 1.62

if x > y: 
  print("x is greater than y")
```

## else

```{python}
x = 3.14
y = 4.62

if x > y: 
  print("x is greater than y")
else:
  print("y is greater or equal than x")

```

## elif

```{python}
x = 3.14
y = 10.62

if x > y: 
  print("x is greater than y")
elif x < y:
  print("y is greater than x")
else:
  print("y and x are equal")

```

## while

```{python}
i = 1
while i < 6:
  print(i)
  i += 1
```

With the break statement we can stop the loop even if the while condition is true.

```{python}
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1 
```

## for

```{python}
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
```

With the continue statement we can stop the current iteration of the loop, and continue with the next.

```{python}
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)
```

To loop through a set of code a specified number of times, we can use the `range()` function.

```{python}
for x in range(6):
  print(x)
```

# Modules

In python, functions and other resources are coded in components called modules. We can create our own modules from our scripts. 

The `math` module includes several functions that perform basic mathematical operations.

To import a module, use the `import` statement. This code imports and lists the resources included in the `math` module

```{python}
import math
print dir(math)

help(math.sin)

print math.sin(math.pi)
```

To import individual resources we  can use the following.

```{python}
from math import pi, e

print e
print pi

```

# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

## Setting up

To install numpy, open the anaconda prompt, and type the following.

```{bash, eval=F}
conda install -c conda-forge numpy
```

That's it! To check if everything went down smoothly, we can try importing the numpy module.

```{python}
import numpy as np # No error means it's alright

print np.arange(5)
```

## Arrays

There are several ways to create arrays.

  1. From a regular python list or tuple, using the `array` function.
```{python}
import numpy as np
a = np.array([2, 3, 4])
print a
print type(a)
print a.dtype
b = np.array([1.2, 3.5, 4])
print b.dtype
```
  
2. Sequences of sequences to 2D arrays.

```{python}
import numpy as np
b = np.array([(1.5,2,3), (4,5,6)])
print b
print b.shape
```

3. **Zero**, **one** and **empty** arrays

```{python}
import numpy as np

zero_array = np.zeros( (3,4) ) # shape
print zero_array

one_array = np.ones( (2,3,4), dtype=np.int8 ) # dtype can also be specified
print one_array

empty_array = np.empty( (2,3) ) # uninitialized, output may vary
print empty_array
```

4. With `arange()` and `linspace()`

```{python}
import numpy as np

print np.arange(0, 2, 0.3) # from, to, step
print np.linspace(0, 2, 9) # from, to, out length
```
5. With `.reshape()`

```{python}
import numpy as np

b = np.arange(24)
b = b.reshape(2,3,4) # 3D array

print b
```

## Basic operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

```{python}
import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print b

c = a - b
print c

print b**2

print a < 35
```
The matrix product can be performed using the `dot()` function.

```{python}
import numpy as np

a = np.array([2, 7.1, 4.2, 5.4, 8.3, 9.1]).reshape(2,3)
b = np.arange(9).reshape(3,3)
c = np.arange(3)

print a*c
print a.dot(c) 
print np.dot(a,b) # another way of computing matrix product
```

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the `ndarray` class.

```{python}
import numpy as np
a = np.array([2, 7.1, 4.2, 5.4, 8.3, 9.1]).reshape(2,3)

print a.sum()
print a.max()
print a.var()

```

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the `axis` parameter you can apply an operation along the specified axis of an array.

```{python}
import numpy as np
a = np.array([2, 7.1, 4.2, 5.4, 8.3, 9.1]).reshape(2,3)

print a
print a.sum(axis=0) 
print a.sum(axis=1) 
print a.cumsum(axis=0)
```

## Indexing

+ One-dimensional arrays can be indexed like lists and other python sequences.

```{python}
import numpy as np

a = np.arange(10)**3
print a

print a[2:5] 
print a[:6:2] # equiv. to a[0:6:2] (from start to pos. 6, exclusive, every 2nd element)
print a[3: :2] # equiv. a[3:10:2]
print a[ : :-1] # reversed a

```

+ Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas.

```{python}
import numpy as np

b = np.random.random((3,4))
print b

print b[2,3]
print b[:2, 1]
print b[:, 0]
print b[:,(0,2)]

print b[-1] # equiv. b[-1,:] the last row
```

Iterating over multidimensional arrays is done with respect to the first axis. However, if one wants to perform an operation on each element in the array, one can use the `flat` attribute which is an iterator over all the elements of the array.

```{python}
import numpy as np

b = np.random.random((3,4))

for row in b:
  print row


for element in b.flat:
  print element


```

## Shape manipulation

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array

```{python}
import numpy as np

a = np.round(np.random.random((3,4)), 2)
print a

print a.shape

print a.T # transpose matrix

print a.reshape(6,2)

print a.ravel() # returns the array, flattened

print a.reshape(4, -1) # dim 2 is automatically calculated.

```

On the other hand, the `ndarray.resize` method modifies the array itself.

```{python}
import numpy as np

a = np.round(np.random.random((3,4)), 2)
print a

a.resize((2,6))
print a

```


Several arrays can be stacked together along different axes.

```{python}
import numpy as np

a = np.round(np.random.random((2,2)), 2)
b = np.round(np.random.random((2,2)), 2)

print a
print b

print np.vstack((a,b))
print np.hstack((a,b))
print np.concatenate((a,b), axis=0)
print np.concatenate((a,b), axis=1)
```

Conversely, we can split an array along some axis, with `hsplit`, `vsplit` and `array_split`.

```{python}
import numpy as np

a = np.round(np.random.random((2,12)), 2)

print a
print np.hsplit(a, 3) # split into 3 
print np.hsplit(a, (3,8)) # split ater 3rd and 8th column



```

